### ISSUE TITLE
320*240 depth image with wrong data

### ISSUE THREAD

**Issue by BingbingWang** [intel-ros/realsense#53]
### System Configuration

| Version          | Your Configuration   |
|:---------------- |:---------------------|
| Operating System | Ubuntu14.04.4 LTS               |
| Kernel           | 4.4.0-040400-generic                |
| Backend          | video4linux                  |
| ROS              | Indigo                  |
| ROS RealSense    | 1.1.0           |
| librealsense     | 0.9.1             |
| R200 Firmware    | 1.0.72.06              |

I subscribe the /camera/depth/image_raw topic to get depth image but the depth data seems wrong. So I just tested the depth data in the realsense_camera_nodelet.cpp. In function "RealsenseNodelet::prepareStreamData", copy the depth data and save the depth image. The 360_480 depth images looks fine but when I change the resolution to 240_320, the depth image seems to be wrong, as
![test320_240](https://cloud.githubusercontent.com/assets/20057790/16217785/4b3175cc-37a9-11e6-9373-03d0b90cef0a.png)

**Comment by rjingar** [comment]
That's weird. With the same system configuration and resolution (320x240) I could not reproduce the issue. Depth stream works fine for me for all supported resolutions.

Instead of saving the image it would be easier to verify by viewing live stream using rviz or image_view. Please refer readme for the commands to view stream and let me know if it works.

**Comment by BingbingWang** [comment]
Thanks for suggestions.
I tried this and the images i got in rviz and image_view are still not right. I just change the depth_width and depth_height in realsense_camera_nodelet.h and catkin_make again, then `roslaunch realsense_camera realsense_r200_nodelet_standalone_preset.launch` in trerminal. Is this method right?

**Comment by BingbingWang** [comment]
sorry I just clicked the "close" by mistake... new to github issues...

**Comment by rjingar** [comment]
There is no need to change code. Instead of preset launch file, please use manual launch file and you can modify height/width/fps etc. Please refer 'Static Parameters' sections for details about available parameters. 

Ex: you can set mode to 'manual' instead of 'preset' in launch file (i.e. manual launch file) and use following params.

depth_height (int, default: 360)
        Specify the depth camera height resolution.
depth_width (int, default: 480)
        Specify the depth camera width resolution.

**Comment by rjingar** [comment]
Looks like you were able to run it with suggested params. Please reopen if you are still seeing this issue.
